In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sqlalchemy import create_engine
#Imports the function to load environment variables from an `.env` file into the Python environment
from dotenv import load_dotenv

# Imports the built-in `os` module to access those environment variables using os.getenv()
import os

load_dotenv(dotenv_path="C:/Users/Admin/project-data/Non_elec_energy_analysis/Energy-Analysis/.env")

# Retrieves the PostgreSQL credentials from the `.env` file environment variable 
username = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host     = os.getenv("DB_HOST")
port     = os.getenv("DB_PORT")
database = os.getenv("DB_NAME")

# Create the SQLAlchemy engine
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# check if the connection works
with engine.connect() as connection:
    print("SQLAlchemy connected!")

SQLAlchemy connected!

In [3]:
owid_raw = pd.read_csv(r"C:\Users\Admin\project-data\Non_elec_energy_analysis\Energy-Analysis\data\owid-energy-data.csv")

In [4]:
pd.set_option('display.max_info_columns', 200)

In [5]:
owid_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 23195 entries, 0 to 23194
Data columns (total 130 columns):
 #    Column                                        Non-Null Count  Dtype
---   ------                                        --------------  -----
 0    country                                       23195 non-null  str
 1    year                                          23195 non-null  int64
 2    iso_code                                      17099 non-null  str
 3    population                                    18729 non-null  float64
 4    gdp                                           11780 non-null  float64
 5    biofuel_cons_change_pct                       2070 non-null   float64
 6    biofuel_cons_change_twh                       7903 non-null   float64
 7    biofuel_cons_per_capita                       6338 non-null   float64
 8    biofuel_consumption                           8057 non-null   float64
 9    biofuel_elec_per_capita                       5753 non-null   float64
 10   biofuel_electricity                           6063 non-null   float64
 11   biofuel_share_elec                            6040 non-null   float64
 12   biofuel_share_energy                          6379 non-null   float64
 13   carbon_intensity_elec                         5737 non-null   float64
 14   coal_cons_change_pct                          5827 non-null   float64
 15   coal_cons_change_twh                          6293 non-null   float64
 16   coal_cons_per_capita                          5145 non-null   float64
 17   coal_consumption                              6405 non-null   float64
 18   coal_elec_per_capita                          6265 non-null   float64
 19   coal_electricity                              7175 non-null   float64
 20   coal_prod_change_pct                          9922 non-null   float64
 21   coal_prod_change_twh                          16562 non-null  float64
 22   coal_prod_per_capita                          14808 non-null  float64
 23   coal_production                               16822 non-null  float64
 24   coal_share_elec                               7072 non-null   float64
 25   coal_share_energy                             6379 non-null   float64
 26   electricity_demand                            6102 non-null   float64
 27   electricity_demand_per_capita                 5792 non-null   float64
 28   electricity_generation                        7981 non-null   float64
 29   electricity_share_energy                      4415 non-null   float64
 30   energy_cons_change_pct                        12745 non-null  float64
 31   energy_cons_change_twh                        12978 non-null  float64
 32   energy_per_capita                             11086 non-null  float64
 33   energy_per_gdp                                7882 non-null   float64
 34   fossil_cons_change_pct                        6267 non-null   float64
 35   fossil_cons_change_twh                        6293 non-null   float64
 36   fossil_elec_per_capita                        6277 non-null   float64
 37   fossil_electricity                            7187 non-null   float64
 38   fossil_energy_per_capita                      5145 non-null   float64
 39   fossil_fuel_consumption                       6405 non-null   float64
 40   fossil_share_elec                             7084 non-null   float64
 41   fossil_share_energy                           6379 non-null   float64
 42   gas_cons_change_pct                           5643 non-null   float64
 43   gas_cons_change_twh                           6293 non-null   float64
 44   gas_consumption                               6405 non-null   float64
 45   gas_elec_per_capita                           6152 non-null   float64
 46   gas_electricity                               7062 non-null   float64
 47   gas_energy_per_capita                         5145 non-null   float64
 48   gas_prod_change_pct                           8103 non-null   float64
 49   gas_prod_change_twh                           16990 non-null  float64
 50   gas_prod_per_capita                           15028 non-null  float64
 51   gas_production                                17251 non-null  float64
 52   gas_share_elec                                6959 non-null   float64
 53   gas_share_energy                              6379 non-null   float64
 54   greenhouse_gas_emissions                      5760 non-null   float64
 55   hydro_cons_change_pct                         5686 non-null   float64
 56   hydro_cons_change_twh                         6293 non-null   float64
 57   hydro_consumption                             6405 non-null   float64
 58   hydro_elec_per_capita                         8337 non-null   float64
 59   hydro_electricity                             9907 non-null   float64
 60   hydro_energy_per_capita                       5145 non-null   float64
 61   hydro_share_elec                              7924 non-null   float64
 62   hydro_share_energy                            6379 non-null   float64
 63   low_carbon_cons_change_pct                    5902 non-null   float64
 64   low_carbon_cons_change_twh                    6293 non-null   float64
 65   low_carbon_consumption                        6405 non-null   float64
 66   low_carbon_elec_per_capita                    8356 non-null   float64
 67   low_carbon_electricity                        9926 non-null   float64
 68   low_carbon_energy_per_capita                  5145 non-null   float64
 69   low_carbon_share_elec                         7943 non-null   float64
 70   low_carbon_share_energy                       6379 non-null   float64
 71   net_elec_imports                              5792 non-null   float64
 72   net_elec_imports_share_demand                 5769 non-null   float64
 73   nuclear_cons_change_pct                       2579 non-null   float64
 74   nuclear_cons_change_twh                       7717 non-null   float64
 75   nuclear_consumption                           7859 non-null   float64
 76   nuclear_elec_per_capita                       9041 non-null   float64
 77   nuclear_electricity                           10625 non-null  float64
 78   nuclear_energy_per_capita                     6585 non-null   float64
 79   nuclear_share_elec                            7852 non-null   float64
 80   nuclear_share_energy                          6379 non-null   float64
 81   oil_cons_change_pct                           6267 non-null   float64
 82   oil_cons_change_twh                           6293 non-null   float64
 83   oil_consumption                               6405 non-null   float64
 84   oil_elec_per_capita                           6216 non-null   float64
 85   oil_electricity                               7126 non-null   float64
 86   oil_energy_per_capita                         5145 non-null   float64
 87   oil_prod_change_pct                           10182 non-null  float64
 88   oil_prod_change_twh                           17729 non-null  float64
 89   oil_prod_per_capita                           15574 non-null  float64
 90   oil_production                                17992 non-null  float64
 91   oil_share_elec                                7023 non-null   float64
 92   oil_share_energy                              6379 non-null   float64
 93   other_renewable_consumption                   6405 non-null   float64
 94   other_renewable_electricity                   9851 non-null   float64
 95   other_renewable_exc_biofuel_electricity       5490 non-null   float64
 96   other_renewables_cons_change_pct              3988 non-null   float64
 97   other_renewables_cons_change_twh              6293 non-null   float64
 98   other_renewables_elec_per_capita              8281 non-null   float64
 99   other_renewables_elec_per_capita_exc_biofuel  5180 non-null   float64
 100  other_renewables_energy_per_capita            5145 non-null   float64
 101  other_renewables_share_elec                   7868 non-null   float64
 102  other_renewables_share_elec_exc_biofuel       5467 non-null   float64
 103  other_renewables_share_energy                 6379 non-null   float64
 104  per_capita_electricity                        6831 non-null   float64
 105  primary_energy_consumption                    13255 non-null  float64
 106  renewables_cons_change_pct                    5895 non-null   float64
 107  renewables_cons_change_twh                    6293 non-null   float64
 108  renewables_consumption                        6405 non-null   float64
 109  renewables_elec_per_capita                    8356 non-null   float64
 110  renewables_electricity                        9926 non-null   float64
 111  renewables_energy_per_capita                  5145 non-null   float64
 112  renewables_share_elec                         7943 non-null   float64
 113  renewables_share_energy                       6379 non-null   float64
 114  solar_cons_change_pct                         2515 non-null   float64
 115  solar_cons_change_twh                         6293 non-null   float64
 116  solar_consumption                             6405 non-null   float64
 117  solar_elec_per_capita                         8373 non-null   float64
 118  solar_electricity                             9943 non-null   float64
 119  solar_energy_per_capita                       5145 non-null   float64
 120  solar_share_elec                              7940 non-null   float64
 121  solar_share_energy                            6379 non-null   float64
 122  wind_cons_change_pct                          2798 non-null   float64
 123  wind_cons_change_twh                          6293 non-null   float64
 124  wind_consumption                              6405 non-null   float64
 125  wind_elec_per_capita                          8301 non-null   float64
 126  wind_electricity                              9871 non-null   float64
 127  wind_energy_per_capita                        5145 non-null   float64
 128  wind_share_elec                               7868 non-null   float64
 129  wind_share_energy                             6379 non-null   float64
dtypes: float64(127), int64(1), str(2)
memory usage: 23.0 MB

In [6]:
countries = ["Nigeria", "South Africa", "Brazil", "Indonesia", "Mexico"]

In [7]:
owid = owid_raw[owid_raw["country"].isin(countries)]

In [8]:
owid = owid.reset_index(drop=True)

In [9]:
owid.info()

<class 'pandas.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 130 columns):
 #    Column                                        Non-Null Count  Dtype
---   ------                                        --------------  -----
 0    country                                       625 non-null    str
 1    year                                          625 non-null    int64
 2    iso_code                                      625 non-null    str
 3    population                                    625 non-null    float64
 4    gdp                                           508 non-null    float64
 5    biofuel_cons_change_pct                       118 non-null    float64
 6    biofuel_cons_change_twh                       295 non-null    float64
 7    biofuel_cons_per_capita                       300 non-null    float64
 8    biofuel_consumption                           300 non-null    float64
 9    biofuel_elec_per_capita                       124 non-null    float64
 10   biofuel_electricity                           124 non-null    float64
 11   biofuel_share_elec                            124 non-null    float64
 12   biofuel_share_energy                          240 non-null    float64
 13   carbon_intensity_elec                         124 non-null    float64
 14   coal_cons_change_pct                          236 non-null    float64
 15   coal_cons_change_twh                          236 non-null    float64
 16   coal_cons_per_capita                          240 non-null    float64
 17   coal_consumption                              240 non-null    float64
 18   coal_elec_per_capita                          185 non-null    float64
 19   coal_electricity                              185 non-null    float64
 20   coal_prod_change_pct                          581 non-null    float64
 21   coal_prod_change_twh                          612 non-null    float64
 22   coal_prod_per_capita                          617 non-null    float64
 23   coal_production                               617 non-null    float64
 24   coal_share_elec                               185 non-null    float64
 25   coal_share_energy                             240 non-null    float64
 26   electricity_demand                            124 non-null    float64
 27   electricity_demand_per_capita                 124 non-null    float64
 28   electricity_generation                        185 non-null    float64
 29   electricity_share_energy                      160 non-null    float64
 30   energy_cons_change_pct                        279 non-null    float64
 31   energy_cons_change_twh                        279 non-null    float64
 32   energy_per_capita                             284 non-null    float64
 33   energy_per_gdp                                275 non-null    float64
 34   fossil_cons_change_pct                        236 non-null    float64
 35   fossil_cons_change_twh                        236 non-null    float64
 36   fossil_elec_per_capita                        185 non-null    float64
 37   fossil_electricity                            185 non-null    float64
 38   fossil_energy_per_capita                      240 non-null    float64
 39   fossil_fuel_consumption                       240 non-null    float64
 40   fossil_share_elec                             185 non-null    float64
 41   fossil_share_energy                           240 non-null    float64
 42   gas_cons_change_pct                           230 non-null    float64
 43   gas_cons_change_twh                           236 non-null    float64
 44   gas_consumption                               240 non-null    float64
 45   gas_elec_per_capita                           185 non-null    float64
 46   gas_electricity                               185 non-null    float64
 47   gas_energy_per_capita                         240 non-null    float64
 48   gas_prod_change_pct                           344 non-null    float64
 49   gas_prod_change_twh                           532 non-null    float64
 50   gas_prod_per_capita                           537 non-null    float64
 51   gas_production                                537 non-null    float64
 52   gas_share_elec                                185 non-null    float64
 53   gas_share_energy                              240 non-null    float64
 54   greenhouse_gas_emissions                      124 non-null    float64
 55   hydro_cons_change_pct                         236 non-null    float64
 56   hydro_cons_change_twh                         236 non-null    float64
 57   hydro_consumption                             240 non-null    float64
 58   hydro_elec_per_capita                         265 non-null    float64
 59   hydro_electricity                             265 non-null    float64
 60   hydro_energy_per_capita                       240 non-null    float64
 61   hydro_share_elec                              185 non-null    float64
 62   hydro_share_energy                            240 non-null    float64
 63   low_carbon_cons_change_pct                    236 non-null    float64
 64   low_carbon_cons_change_twh                    236 non-null    float64
 65   low_carbon_consumption                        240 non-null    float64
 66   low_carbon_elec_per_capita                    265 non-null    float64
 67   low_carbon_electricity                        265 non-null    float64
 68   low_carbon_energy_per_capita                  240 non-null    float64
 69   low_carbon_share_elec                         185 non-null    float64
 70   low_carbon_share_energy                       240 non-null    float64
 71   net_elec_imports                              124 non-null    float64
 72   net_elec_imports_share_demand                 124 non-null    float64
 73   nuclear_cons_change_pct                       115 non-null    float64
 74   nuclear_cons_change_twh                       295 non-null    float64
 75   nuclear_consumption                           300 non-null    float64
 76   nuclear_elec_per_capita                       300 non-null    float64
 77   nuclear_electricity                           300 non-null    float64
 78   nuclear_energy_per_capita                     300 non-null    float64
 79   nuclear_share_elec                            185 non-null    float64
 80   nuclear_share_energy                          240 non-null    float64
 81   oil_cons_change_pct                           236 non-null    float64
 82   oil_cons_change_twh                           236 non-null    float64
 83   oil_consumption                               240 non-null    float64
 84   oil_elec_per_capita                           185 non-null    float64
 85   oil_electricity                               185 non-null    float64
 86   oil_energy_per_capita                         240 non-null    float64
 87   oil_prod_change_pct                           420 non-null    float64
 88   oil_prod_change_twh                           532 non-null    float64
 89   oil_prod_per_capita                           537 non-null    float64
 90   oil_production                                537 non-null    float64
 91   oil_share_elec                                185 non-null    float64
 92   oil_share_energy                              240 non-null    float64
 93   other_renewable_consumption                   240 non-null    float64
 94   other_renewable_electricity                   265 non-null    float64
 95   other_renewable_exc_biofuel_electricity       49 non-null     float64
 96   other_renewables_cons_change_pct              167 non-null    float64
 97   other_renewables_cons_change_twh              236 non-null    float64
 98   other_renewables_elec_per_capita              265 non-null    float64
 99   other_renewables_elec_per_capita_exc_biofuel  49 non-null     float64
 100  other_renewables_energy_per_capita            240 non-null    float64
 101  other_renewables_share_elec                   185 non-null    float64
 102  other_renewables_share_elec_exc_biofuel       49 non-null     float64
 103  other_renewables_share_energy                 240 non-null    float64
 104  per_capita_electricity                        185 non-null    float64
 105  primary_energy_consumption                    284 non-null    float64
 106  renewables_cons_change_pct                    236 non-null    float64
 107  renewables_cons_change_twh                    236 non-null    float64
 108  renewables_consumption                        240 non-null    float64
 109  renewables_elec_per_capita                    265 non-null    float64
 110  renewables_electricity                        265 non-null    float64
 111  renewables_energy_per_capita                  240 non-null    float64
 112  renewables_share_elec                         185 non-null    float64
 113  renewables_share_energy                       240 non-null    float64
 114  solar_cons_change_pct                         86 non-null     float64
 115  solar_cons_change_twh                         236 non-null    float64
 116  solar_consumption                             240 non-null    float64
 117  solar_elec_per_capita                         265 non-null    float64
 118  solar_electricity                             265 non-null    float64
 119  solar_energy_per_capita                       240 non-null    float64
 120  solar_share_elec                              185 non-null    float64
 121  solar_share_energy                            240 non-null    float64
 122  wind_cons_change_pct                          98 non-null     float64
 123  wind_cons_change_twh                          236 non-null    float64
 124  wind_consumption                              240 non-null    float64
 125  wind_elec_per_capita                          265 non-null    float64
 126  wind_electricity                              265 non-null    float64
 127  wind_energy_per_capita                        240 non-null    float64
 128  wind_share_elec                               185 non-null    float64
 129  wind_share_energy                             240 non-null    float64
dtypes: float64(127), int64(1), str(2)
memory usage: 634.9 KB

In [10]:
owid.isna().sum().sort_values()

country                                           0
year                                              0
iso_code                                          0
population                                        0
coal_production                                   8
                                               ...
wind_cons_change_pct                            527
solar_cons_change_pct                           539
other_renewable_exc_biofuel_electricity         576
other_renewables_share_elec_exc_biofuel         576
other_renewables_elec_per_capita_exc_biofuel    576
Length: 130, dtype: int64

In [11]:
num_cols = owid.select_dtypes(include=['float64', 'int64']).columns

In [12]:
owid[num_cols] = owid[num_cols].fillna(0)

In [13]:
owid.isna().sum().sort_values()

country                   0
year                      0
iso_code                  0
population                0
gdp                       0
                         ..
wind_elec_per_capita      0
wind_electricity          0
wind_energy_per_capita    0
wind_share_elec           0
wind_share_energy         0
Length: 130, dtype: int64

In [14]:
columns_needed = [
    "country",
    "iso_code",
    "year",
    "population",
    "gdp",

    "primary_energy_consumption",
    "energy_per_capita",
    "energy_per_gdp",

    "oil_consumption",
    "gas_consumption",
    "coal_consumption",
    "biofuel_consumption",
    "renewables_consumption",
    "low_carbon_consumption",
    "fossil_fuel_consumption",
    "fossil_share_energy",
    "low_carbon_share_energy",
    
    "greenhouse_gas_emissions"
]

In [15]:
owid = owid[columns_needed]

In [16]:
owid

,country,iso_code,year,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp,oil_consumption,gas_consumption,coal_consumption,biofuel_consumption,renewables_consumption,low_carbon_consumption,fossil_fuel_consumption,fossil_share_energy,low_carbon_share_energy,greenhouse_gas_emissions
0,Brazil,BRA,1900,18058538.0,1.571802e+10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
1,Brazil,BRA,1901,18463951.0,1.728848e+10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
2,Brazil,BRA,1902,18869255.0,1.729822e+10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
3,Brazil,BRA,1903,19274237.0,1.764560e+10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
4,Brazil,BRA,1904,19687910.0,1.798087e+10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,South Africa,ZAF,2020,60562321.0,6.758717e+11,1399.597,23110.025,2.071,274.014,39.705,1022.687,1.271,36.073,60.525,1336.406,95.667,4.333,183.66
621,South Africa,ZAF,2021,61502553.0,7.090779e+11,1405.650,22855.152,1.982,288.233,41.993,996.153,1.267,45.540,75.971,1326.379,94.583,5.417,181.88
622,South Africa,ZAF,2022,62378377.0,7.235593e+11,1346.169,21580.703,1.860,287.800,42.695,938.539,1.176,48.990,73.806,1269.034,94.504,5.496,174.20
623,South Africa,ZAF,2023,63212339.0,0.000000e+00,1367.989,21641.166,0.000,290.035,47.449,955.848,1.015,51.261,71.017,1293.333,94.795,5.205,165.77
624,South Africa,ZAF,2024,64007137.0,0.000000e+00,1362.492,21286.564,0.000,267.992,47.710,976.233,1.024,48.347,67.371,1291.935,95.044,4.956,173.54

In [17]:
owid = owid.rename(columns={
      "primary_energy_consumption": "total_energy_twh",
    "energy_per_capita": "energy_per_capita_kwh",
    "energy_per_gdp": "energy_intensity",
    "fossil_fuel_consumption": "fossil_consumption_twh",
    "low_carbon_consumption": "low_carbon_consumption_twh",
    "renewables_consumption": "renewables_consumption_twh",
    "oil_consumption": "oil_consumption_twh",
    "gas_consumption": "gas_consumption_twh",
    "coal_consumption": "coal_consumption_twh",
    "biofuel_consumption": "biofuel_consumption_twh",
    "greenhouse_gas_emissions": "co2_emissions"
})

In [18]:
owid

,country,iso_code,year,population,gdp,total_energy_twh,energy_per_capita_kwh,energy_intensity,oil_consumption_twh,gas_consumption_twh,coal_consumption_twh,biofuel_consumption_twh,renewables_consumption_twh,low_carbon_consumption_twh,fossil_consumption_twh,fossil_share_energy,low_carbon_share_energy,co2_emissions
0,Brazil,BRA,1900,18058538.0,1.571802e+10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
1,Brazil,BRA,1901,18463951.0,1.728848e+10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
2,Brazil,BRA,1902,18869255.0,1.729822e+10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
3,Brazil,BRA,1903,19274237.0,1.764560e+10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
4,Brazil,BRA,1904,19687910.0,1.798087e+10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,South Africa,ZAF,2020,60562321.0,6.758717e+11,1399.597,23110.025,2.071,274.014,39.705,1022.687,1.271,36.073,60.525,1336.406,95.667,4.333,183.66
621,South Africa,ZAF,2021,61502553.0,7.090779e+11,1405.650,22855.152,1.982,288.233,41.993,996.153,1.267,45.540,75.971,1326.379,94.583,5.417,181.88
622,South Africa,ZAF,2022,62378377.0,7.235593e+11,1346.169,21580.703,1.860,287.800,42.695,938.539,1.176,48.990,73.806,1269.034,94.504,5.496,174.20
623,South Africa,ZAF,2023,63212339.0,0.000000e+00,1367.989,21641.166,0.000,290.035,47.449,955.848,1.015,51.261,71.017,1293.333,94.795,5.205,165.77
624,South Africa,ZAF,2024,64007137.0,0.000000e+00,1362.492,21286.564,0.000,267.992,47.710,976.233,1.024,48.347,67.371,1291.935,95.044,4.956,173.54

In [ ]:
owid.to_sql("energy_master",
           engine,
           if_exists="replace",
           index=False
           )
print("energy data successfully loaded into PostgreSQL.")

IndentationError: unexpected indent (2056646305.py, line 2)